version: '3.0'

services:
  api:
    container_name: api
    build: ./
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./src:/app/src
    command: sh -c "npm run migration:generate && npm run start:dev"

  db:
    container_name: db
    build: ./db
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: ["postgres", "-c", "logging_collector=true"]
    networks:
      - app-network
    volumes:
      - pgdb:/var/lib/postgresql/data

volumes:
  pgdb:

networks:
  app-network:
    driver: bridge
