version: '3'
services: 
  api:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    networks:
      - app-network
    command: npm run start:dev
  postgres:
    restart: on-failure
    build: ./postgresdb/
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER={POSTGRES_USER}
      - POSTGRES_PASSWORD={POSTGRES_PASSWORD}
      - POSTGRES_DB={POSTGRES_DB}
    volumes:
      - pgdb:/var/lib/postgresql/data
    networks:
      - app-network
volumes:
  app:
  pgdb:
networks:
  app-network:
    name: custom-network
    driver: bridge